server:
  port: 8080
spring:
  datasource:
    username: root
    password: zyf20020523.
    url: jdbc:mysql://127.0.0.1:3306/coursemanagement?serverTimezone=UTC
  redis:
    port: 6379
  servlet: #文件
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
  mail:
    host: smtp.qq.com
    port: 587
    username: 1476203673@qq.com
    password: qqntmomixopehjhi
    default-encoding: UTF-8 # 配置邮件编码
    properties: 
      mail:
        smpt:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          debug: true
    from: 1476203673@qq.com
file:
  upload:
    dir: D:/test
    disableTypes: dll,exe
logging:
  level:
    com.hbut: debug
  file:
    path: D:/code/logs/
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

